[package]
name = "simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = "1.0"
anyhow = "1.0.100"
camino = "1.1"
snafu = "0.8.9"
elf = "0.8.0"

[build-dependencies]
anyhow = "1.0.100"
xshell = "0.2.7"
cxx-build = "1.0"
glob = "0.3.3"
