soc:
  enableDebug: false
  uarts:
    - name: uart0
      baseAddr: 0x00100000
      enabled: true
    - name: uart1
      baseAddr: 0x00100010
      enabled: true
cores:
  - micro:
      xlen: 32
memory:
  - tcm:
      size: 65536
      startAddress: 0x80000000
