clusters:
  - coreType: micro
    isa: rv32im_zicsr
    numCores: 1
io:
  - type: uart
    name: uart0
    baseAddr: 0x00100000
  - type: uart
    name: uart1
    baseAddr: 0x00100010
memories:
  - type: tcm
    baseAddress: 0x80000000
    length: 65536
