clusters:
  - coreType: micro
    isa: rv32i_zmmul_zicsr
    numCores: 1
io:
  - type: uart
    name: uart0
    baseAddr: 0x00100000
  - type: uart
    name: uart1
    baseAddr: 0x00100010
memories:
  - type: tcm
    baseAddress: 0x80000000
    length: 65536
timer:
  baseAddr: 0x02000000
  enabled: true
