name: Continuous Integration

on:
  push:
    tags: ["*"]
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Set caching env vars
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
      - name: Setup Spike
        run: |
          sudo apt-get install -yqq device-tree-compiler libboost-regex-dev libboost-system-dev
          git clone https://github.com/riscv-software-src/riscv-isa-sim.git
          cd riscv-isa-sim
          mkdir build && cd build
          ../configure CC="${SCCACHE_PATH} gcc" CXX="${SCCACHE_PATH} g++" --prefix=/opt/spike
          sudo make install
          echo "/opt/spike/bin" >> $GITHUB_PATH
          cd ../../
          rm -rf riscv-isa-sim
      - name: Setup RISC-V toolchain
        run: |
          wget https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2025.11.21/riscv32-elf-ubuntu-24.04-gcc.tar.xz
          mkdir -p /opt/riscv32/
          tar -xvf riscv32-elf-ubuntu-24.04-gcc.tar.xz -C /opt/riscv32/
          echo "/opt/riscv32/riscv/bin" >> $GITHUB_PATH
          rm riscv32-elf-ubuntu-24.04-gcc.tar.xz
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: sbt
      - name: Setup Dependencies
        run: |
          sudo apt-get install verilator
          verilator --version
      - name: Unit tests
        run: ./mill _.test
      - name: Integration tests
        run: cargo test

  formatting:
    name: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
